project:
  type: book
  output-dir: docs

book:
  title: "Code Book"
  author: "Chrissy Roberts"
  date: "3/21/2023"
  downloads: [pdf]

  chapters:
  - index.qmd

  - part: "R / RStudio"
    chapters:
      # - extract_model_from_geom_smooth.qmd
       - update_R.qmd
       - utf8_encoding.qmd
       - remove_accents.qmd
       - text_to_speech_R.qmd
       - UK_Postcodes.qmd
       - photo_cleaning.qmd

  - part: "Statistics"
    chapters:
       - Interrupted_Time_Series.qmd
       - new_lm_predict_left_predict_right.qmd
       - power_calc_gen_case_control.qmd
       - Diagnostics_Power_Calculation.qmd
       - 95CI_point_estimate.qmd
       - hazratio_chart.qmd

  - part: "Laboratory Methods"
    chapters:
       - Digital_Luminex.qmd

  - part: "ODK"
    chapters:
       - ruODK_basics.qmd
       - diva_gis.qmd
       - ODK_geofencing.qmd

  - part: "tables"
    chapters:
       - Univariate_regressions_reported_as_a_table.qmd

  - part: "Cribsheet [Other people's work]"
    chapters:
       - Akaike_Information_Criterion.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual



