project:
  type: book
  output-dir: docs

book:
  title: "Code Book"
  author: "Chrissy Roberts"
  date: "3/21/2023"
  downloads: [pdf]

  chapters:
  - index.qmd

  - part: "ODK"
    chapters:
       - examples/ruODK_basics.qmd

  - part: "Time Series"
    chapters:
       - examples/Interrupted_Time_Series.qmd
       - examples/new_lm_predict_left_predict_right.qmd

  - part: "R cleverness"
    chapters:
       - examples/extract_model_from_geom_smooth.qmd
       - examples/95CI_point_estimate.qmd
       - examples/update_R.qmd

  - part: "ggplot, charts, images"

  - part: "tables"
    chapters:
       - examples/Univariate_regressions_reported_as_a_table.qmd


  - part: "Cribsheet [Other people's work]"
    chapters:
       - examples/Akaike_Information_Criterion.qmd


bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual



