project:
  type: book
  output-dir: docs

book:
  title: "Code Book"
  author: "Chrissy Roberts"
  date: "3/21/2023"

  chapters:
  - index.qmd

  - part: "R | RStudio"
    chapters:
       - R_basics.qmd
       - extract_model_from_geom_smooth.qmd
       - filename_changer.qmd
       - Global_Political_Map.qmd
       - Quick_Country_Maps.qmd
       - photo_cleaning.qmd
       - remove_accents.qmd
       - text_to_speech_R.qmd
       - UK_Postcodes.qmd
       - update_R.qmd
       - utf8_encoding.qmd

  - part: "Statistics"
    chapters:
   #    - Cox_PH.qmd
       - Cumulative_Incidence.qmd
       - Interrupted_Time_Series.qmd
       - new_lm_predict_left_predict_right.qmd
       - Diagnostics_Power_Calculation.qmd
       - CI95_point_estimate.qmd
       - hazratio_chart.qmd
       - power_calc_gen_case_control.qmd
       - Principal_Components_Analysis.qmd

  - part: "Laboratory | Field Methods"
    chapters:
       - Consent_Forms_with_QR.qmd
       - Digital_Luminex.qmd
       - Generic_Research_Data_Folder_Design.qmd
       - FPC_Grader.qmd


  - part: "ODK"
    chapters:
       - ODK_Biometrics.qmd
       - ODK_UUID.qmd
       - ruODK_basics.qmd
       - ODK_geofencing.qmd
       - ODK_Pi.qmd
       - Balanced_Prioritisation.qmd
       - XLSForm_Dictionary.qmd
       - CSV_populate_Central.qmd

  - part: "Python, bash and other code"
    chapters:
       - Docker_install_ubuntu.qmd
       - Join_photos_randomly.qmd
       - Whisper_Ai_CPU.qmd

  - part: "Software"
    chapters:
       - Add_QR_Codes_to_PDF.qmd
       - badger2040w.qmd
       - comic2pdf.qmd
       - Computer_Vision.qmd
       - CUPS_Zebra_Printer.qmd
       - remarkable.qmd
       - SayMyName.qmd



bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual



