project:
  type: book
  output-dir: docs

book:
  title: "Code Book"
  author: "Chrissy Roberts"
  date: "3/21/2023"

  chapters:
  - index.qmd

  - part: "R | RStudio"
    chapters:
       - big_data_IO_benchmarks.qmd
       - extract_model_from_geom_smooth.qmd
       - filename_changer.qmd
       - Global_Political_Map.qmd
       - photo_cleaning.qmd
       - remove_accents.qmd
       - text_to_speech_R.qmd
       - UK_Postcodes.qmd
       - update_R.qmd
       - utf8_encoding.qmd



  - part: "Statistics"
    chapters:
       - Interrupted_Time_Series.qmd
       - new_lm_predict_left_predict_right.qmd
       - Diagnostics_Power_Calculation.qmd
       - CI95_point_estimate.qmd
       - hazratio_chart.qmd
       - power_calc_gen_case_control.qmd
       - Principal_Components_Analysis.qmd
       - Univariate_regressions_reported_as_a_table.qmd

  - part: "Laboratory | Field Methods"
    chapters:
       - Univariate_regressions_reported_as_a_table.qmd
       - Consent_Forms_with_QR.qmd
       - Digital_Luminex.qmd
       - Generic_Research_Data_Folder_Design.qmd

  - part: "ODK"
    chapters:
       - ODK_Biometrics.qmd
       - ruODK_basics.qmd
       - diva_gis.qmd
       - ODK_geofencing.qmd
       - ODK_Pi.qmd

  - part: "Python, bash and other code"
    chapters:
       - Docker_install_ubuntu.qmd

  - part: "Cribsheet [Other people's work]"
    chapters:
       - Akaike_Information_Criterion.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo

editor: visual



