project:
  type: book
  output-dir: docs

book:
  title: "Code Book"
  author: "Chrissy Roberts"
  date: "3/21/2023"
  downloads: [pdf]

  chapters:
  - index.qmd

  - part: "Part One"
    chapters:
       - intro.qmd

  - part: "Time Series"
    chapters:
       - examples/Interrupted_Time_Series.qmd

  - part: "R cleverness"
    chapters:
       - examples/extract_model_from_geom_smooth.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual



